import bcrypt from 'bcryptjs';

const data = {
    usuarios: [
        {
            nombre: 'Lluis Martinez',
            email: 'lluismnjr@gmail.com',
            password: bcrypt.hashSync('123456'),
            esAdmin: true
        },
        {
            nombre: 'Georgina Moya',
            email: 'georgina.moyalancho@gmail.com',
            password: bcrypt.hashSync('123456'),
            esAdmin: false
        }
    ],
    productos: [
        {

            nombre: 'Camisa de cuadros',
            slug: 'camisa-de-cuadros',
            categoria: 'Camisas',
            imagen: '/imagenes/p1.jpg',
            precio: 25,
            numeroEnStock: 11,
            marca: 'Untilted',
            valoracion: 4.3,
            numReviews: 10,
            descripcion: 'Esta camisa de cuadros es una mezcla perfecta de estilo casual y elegancia relajada. El patrón de cuadros, en tonos armoniosos, aporta un toque de dinamismo a la prenda, mientras que la paleta de colores cuidadosamente seleccionada garantiza una apariencia equilibrada.'
        },
        {

            nombre: 'Pantalones lisos negros',
            slug: 'pantalones-lisos-negros',
            categoria: 'Pantalones',
            imagen: '/imagenes/p2.jpg',
            precio: 25,
            numeroEnStock: 30,
            marca: 'Untilted',
            valoracion: 4.2,
            numReviews: 7,
            descripcion: 'Estos elegantes pantalones negros son una pieza versátil y atemporal que puede adaptarse a una variedad de ocasiones. Confeccionados con un tejido de alta calidad, ofrecen comodidad y estilo en un solo paquete. Su corte favorecedor resalta la figura mientras proporciona libertad de movimiento.'
        },
        {

            nombre: 'Zapatos negros',
            slug: 'zapatos-negros',
            categoria: 'Calzado',
            imagen: '/imagenes/p3.jpg',
            precio: 20,
            numeroEnStock: 35,
            marca: 'Untilted',
            valoracion: 4.6,
            numReviews: 3,
            descripcion: 'Estos zapatos negros son una declaración de elegancia y estilo refinado. Fabricados con materiales de alta calidad, su diseño combina sofisticación y comodidad.'
        },
        {
            nombre: 'Camiseta blanca gato',
            slug: 'camiseta-blanca-gato',
            categoria: 'Camisetas',
            imagen: '/imagenes/p6.jpg',
            precio: 15,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 3.9,
            numReviews: 12,
            descripcion: 'Esta encantadora camiseta blanca presenta un diseño juguetón y adorable con la figura de un gato. El felino, meticulosamente ilustrado, aporta un toque de dulzura y diversión al atuendo.'
        },
        {
            nombre: 'Pantalones lisos marrones',
            slug: 'pantalones-lisos-marrones',
            categoria: 'Pantalones',
            imagen: '/imagenes/p5.jpg',
            precio: 24,
            numeroEnStock: 23,
            marca: 'Untilted',
            valoracion: 4.4,
            numReviews: 8,
            descripcion: 'Estos elegantes pantalones marrones son una pieza versátil y atemporal que puede adaptarse a una variedad de ocasiones. Confeccionados con un tejido de alta calidad, ofrecen comodidad y estilo en un solo paquete. Su corte favorecedor resalta la figura mientras proporciona libertad de movimiento.'
        },
        {
            nombre: 'Zapatos negros de vestir',
            slug: 'zapatos-negros-de-vestir',
            categoria: 'Calzado',
            imagen: '/imagenes/p4.jpg',
            precio: 30,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 4.7,
            numReviews: 15,
            descripcion: 'Estos zapatos negros son una declaración de elegancia y estilo refinado. Fabricados con materiales de alta calidad, su diseño combina sofisticación y comodidad.'
        },
        {
            nombre: 'Jersei negro de cuello alto',
            slug: 'jersei-negro-de-cuello-alto',
            categoria: 'Jerseis',
            imagen: '/imagenes/p7.jpg',
            precio: 27,
            numeroEnStock: 12,
            marca: 'Untilted',
            valoracion: 4.9,
            numReviews: 23,
            descripcion: 'Este jersey negro de cuello alto es la elección perfecta para mantenerte abrigado con estilo. Su diseño clásico y versátil lo convierte en un básico esencial para tu guardarropa. Fabricado con un tejido suave y cómodo, este jersey te brinda calidez sin renunciar al look elegante.'
        },
        {
            nombre: 'Jersei rosa',
            slug: 'jersei-rosa',
            categoria: 'Jerseis',
            imagen: '/imagenes/p8.jpg',
            precio: 20,
            numeroEnStock: 18,
            marca: 'Untilted',
            valoracion: 3.9,
            numReviews: 11,
            descripcion: 'Este jersey rosa es la elección perfecta para mantenerte abrigado con estilo. Su diseño clásico y versátil lo convierte en un básico esencial para tu guardarropa. Fabricado con un tejido suave y cómodo, este jersey te brinda calidez sin renunciar al look elegante.'
        },
        {
            nombre: 'Pantalones tejanos azules',
            slug: 'pantalones-tejanos-azules',
            categoria: 'Pantalones',
            imagen: '/imagenes/p9.jpg',
            precio: 15,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 3.2,
            numReviews: 3,
            descripcion: 'Estos tejanos azules son la opción perfecta para un estilo casual y cómodo. Confeccionados con un denim resistente pero suave, estos vaqueros ofrecen versatilidad y durabilidad.'
        },
        {
            nombre: 'Camiseta básica negra',
            slug: 'camiseta-basica-negra',
            categoria: 'Camisetas',
            imagen: '/imagenes/p10.jpg',
            precio: 9,
            numeroEnStock: 25,
            marca: 'Untilted',
            valoracion: 3.5,
            numReviews: 9,
            descripcion: 'Una elección esencial para tu vestuario, esta camiseta básica negra combina simplicidad y estilo. Su diseño atemporal y versátil la convierte en la prenda perfecta para cualquier ocasión. '
        },
        {
            nombre: 'Camiseta diaria negra',
            slug: 'camiseta-diaria-negra',
            categoria: 'Camisetas',
            imagen: '/imagenes/p11.jpg',
            precio: 10,
            numeroEnStock: 23,
            marca: 'Untilted',
            valoracion: 3.4,
            numReviews: 4,
            descripcion: 'Una elección esencial para tu vestuario, esta camiseta diaria negra combina simplicidad y estilo. Su diseño atemporal y versátil la convierte en la prenda perfecta para cualquier ocasión. '
        },
        {
            nombre: 'Jersei gris',
            slug: 'jersei-gris',
            categoria: 'Jerseis',
            imagen: '/imagenes/p12.jpg',
            precio: 20,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 4.2,
            numReviews: 15,
            descripcion: 'Este jersey gris es la elección perfecta para mantenerte abrigado con estilo. Su diseño clásico y versátil lo convierte en un básico esencial para tu guardarropa. Fabricado con un tejido suave y cómodo, este jersey te brinda calidez sin renunciar al look elegante.'
        },
        {
            nombre: 'Camiseta básica blanca',
            slug: 'camiseta-basica-blanca',
            categoria: 'Camisetas',
            imagen: '/imagenes/p13.jpg',
            precio: 7,
            numeroEnStock: 23,
            marca: 'Untilted',
            valoracion: 3.9,
            numReviews: 6,
            descripcion: 'Una elección esencial para tu vestuario, esta camiseta básica blanca combina simplicidad y estilo. Su diseño atemporal y versátil la convierte en la prenda perfecta para cualquier ocasión. '
        },
        {
            nombre: 'Abrigo negro',
            slug: 'abrigo-negro',
            categoria: 'Abrigos',
            imagen: '/imagenes/p14.jpg',
            precio: 40,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 4.6,
            numReviews: 15,
            descripcion: 'Envuélvete en estilo con este elegante abrigo negro. Su diseño clásico y atemporal lo convierte en una pieza imprescindible para tu guardarropa. Confeccionado con atención a los detalles, este abrigo destaca por su versatilidad y capacidad para complementar una amplia variedad de conjuntos.'
        },
        {
            nombre: 'Jersei turquesa',
            slug: 'jersei-turquesa',
            categoria: 'Jerseis',
            imagen: '/imagenes/p15.jpg',
            precio: 20,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 4.3,
            numReviews: 13,
            descripcion: 'Este jersey turquesa es la elección perfecta para mantenerte abrigado con estilo. Su diseño clásico y versátil lo convierte en un básico esencial para tu guardarropa. Fabricado con un tejido suave y cómodo, este jersey te brinda calidez sin renunciar al look elegante.'
        },
        {
            nombre: 'Camiseta blanca tay son',
            slug: 'camiseta-blanca-tay-son',
            categoria: 'Camisetas',
            imagen: '/imagenes/p16.jpg',
            precio: 9,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 4.0,
            numReviews: 12,
            descripcion: 'Una elección esencial para tu vestuario, esta camiseta básica blanca combina simplicidad y estilo. Su diseño atemporal y versátil la convierte en la prenda perfecta para cualquier ocasión. '
        },
        {
            nombre: 'Pantalones azules',
            slug: 'pantalones-azules',
            categoria: 'Pantalones',
            imagen: '/imagenes/p17.jpg',
            precio: 28,
            numeroEnStock: 10,
            marca: 'Untilted',
            valoracion: 3.0,
            numReviews: 6,
            descripcion: 'Estos pantalones azules son la combinación perfecta de comodidad y estilo. Confeccionados en un tono azul vibrante, añadirán un toque fresco a tu colección de ropa. Su diseño versátil los convierte en la elección ideal tanto para ocasiones casuales como para eventos más formales.'
        },
        {
            nombre: 'Falda negra de vestir',
            slug: 'falda-negras-de-vestir',
            categoria: 'Faldas',
            imagen: '/imagenes/p18.jpg',
            precio: 20,
            numeroEnStock: 25,
            marca: 'Untilted',
            valoracion: 5.0,
            numReviews: 22,
            descripcion: 'La falda negra para hombre es una prenda audaz y moderna que desafía las convenciones. Confeccionada en un tono negro clásico, esta falda es una expresión única de estilo y autenticidad. Su diseño versátil te permite destacar en cualquier ocasión, ya sea casual o formal.'
        },
        {
            nombre: 'Falda negra de vestir larga',
            slug: 'falda-negras-de-vestir-larga',
            categoria: 'Faldas',
            imagen: '/imagenes/p19.jpg',
            precio: 30,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 4.8,
            numReviews: 20,
            descripcion: 'La falda negra para hombre es una prenda audaz y moderna que desafía las convenciones. Confeccionada en un tono negro clásico, esta falda es una expresión única de estilo y autenticidad. Su diseño versátil te permite destacar en cualquier ocasión, ya sea casual o formal.'
        },
        {
            nombre: 'Falda de cuadros',
            slug: 'falda-de-cuadros',
            categoria: 'Faldas',
            imagen: '/imagenes/p20.jpg',
            precio: 25,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 4.5,
            numReviews: 15,
            descripcion: 'La falda de cuadros para hombre fusiona la elegancia clásica con un toque moderno y vanguardista. Con un patrón de cuadros que aporta estilo y personalidad, esta prenda redefine las normas de la moda masculina. La mezcla de colores y el diseño único hacen de esta falda una elección audaz y llamativa.'
        },
        {
            nombre: 'Camisa de cuadros ocre',
            slug: 'camisa-de-cuadros-ocre',
            categoria: 'Camisas',
            imagen: '/imagenes/p21.jpg',
            precio: 23,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 4.4,
            numReviews: 12,
            descripcion: 'Esta camisa de cuadros es una mezcla perfecta de estilo casual y elegancia relajada. El patrón de cuadros, en tonos armoniosos, aporta un toque de dinamismo a la prenda, mientras que la paleta de colores cuidadosamente seleccionada garantiza una apariencia equilibrada.'
        },
        {
            nombre: 'Camisa de cuadros azul',
            slug: 'camisa-de-cuadros-azul',
            categoria: 'Camisas',
            imagen: '/imagenes/p22.jpg',
            precio: 24,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 3.8,
            numReviews: 9,
            descripcion: 'Esta camisa de cuadros es una mezcla perfecta de estilo casual y elegancia relajada. El patrón de cuadros, en tonos armoniosos, aporta un toque de dinamismo a la prenda, mientras que la paleta de colores cuidadosamente seleccionada garantiza una apariencia equilibrada.'
        },
        {
            nombre: 'Botas crema',
            slug: 'botas-crema',
            categoria: 'Calzado',
            imagen: '/imagenes/p23.jpg',
            precio: 18,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 4.6,
            numReviews: 10,
            descripcion: 'Estas botas en tono crema son el complemento perfecto para destacar tu estilo con elegancia y versatilidad. Su color suave y neutro las convierte en un accesorio fácil de combinar con una variedad de atuendos. Ya sea para pasear por la ciudad o para una ocasión más formal, estas botas añaden un toque de sofisticación a tu look.'
        },
        {
            nombre: 'Jersei blanco de cuello alto',
            slug: 'jersei-blanco-de-cuello-alto',
            categoria: 'Jerseis',
            imagen: '/imagenes/p24.jpg',
            precio: 25,
            numeroEnStock: 12,
            marca: 'Untilted',
            valoracion: 4.7,
            numReviews: 20,
            descripcion: 'Este jersey blanco de cuello alto es la elección perfecta para mantenerte abrigado con estilo. Su diseño clásico y versátil lo convierte en un básico esencial para tu guardarropa. Fabricado con un tejido suave y cómodo, este jersey te brinda calidez sin renunciar al look elegante.'
        },
        {
            nombre: 'Botas de flores',
            slug: 'botas-de-flores',
            categoria: 'Calzado',
            imagen: '/imagenes/p25.jpg',
            precio: 20,
            numeroEnStock: 22,
            marca: 'Untilted',
            valoracion: 4.9,
            numReviews: 29,
            descripcion: 'Estas botas para hombre combinan la robustez de un calzado resistente con un toque distintivo de estilo floral. Con detalles florales cuidadosamente incorporados, estas botas ofrecen una fusión única entre lo rústico y lo elegante.'
        },
        {
            nombre: 'Abrigo ocre',
            slug: 'abrigo-ocre',
            categoria: 'Abrigos',
            imagen: '/imagenes/p26.jpg',
            precio: 40,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 4.5,
            numReviews: 20,
            descripcion: 'Envuélvete en estilo con este elegante abrigo ocre. Su diseño clásico y atemporal lo convierte en una pieza imprescindible para tu guardarropa. Confeccionado con atención a los detalles, este abrigo destaca por su versatilidad y capacidad para complementar una amplia variedad de conjuntos.'
        },
        {
            nombre: 'Jersei turquesa oscuro',
            slug: 'jersei-turquesa-oscuro',
            categoria: 'Jerseis',
            imagen: '/imagenes/p27.jpg',
            precio: 25,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 4.7,
            numReviews: 15,
            descripcion: 'Este jersey turquesa oscuro es la elección perfecta para mantenerte abrigado con estilo. Su diseño clásico y versátil lo convierte en un básico esencial para tu guardarropa. Fabricado con un tejido suave y cómodo, este jersey te brinda calidez sin renunciar al look elegante.'
        },
        {
            nombre: 'Jersei de punto blanco',
            slug: 'jersei-de-punto-blanco',
            categoria: 'Jerseis',
            imagen: '/imagenes/p28.jpg',
            precio: 35,
            numeroEnStock: 25,
            marca: 'Untilted',
            valoracion: 4.8,
            numReviews: 20,
            descripcion: 'Este jersey de punto blanco es la elección perfecta para mantenerte abrigado con estilo. Su diseño clásico y versátil lo convierte en un básico esencial para tu guardarropa. Fabricado con un tejido suave y cómodo, este jersey te brinda calidez sin renunciar al look elegante.'
        },
        {
            nombre: 'Falda negra larga',
            slug: 'falda-negras-larga',
            categoria: 'Faldas',
            imagen: '/imagenes/p29.jpg',
            precio: 15,
            numeroEnStock: 25,
            marca: 'Untilted',
            valoracion: 4.0,
            numReviews: 12,
            descripcion: 'La falda negra para hombre es una prenda audaz y moderna que desafía las convenciones. Confeccionada en un tono negro clásico, esta falda es una expresión única de estilo y autenticidad. Su diseño versátil te permite destacar en cualquier ocasión, ya sea casual o formal.'
        },
        {
            nombre: 'Camiseta básica blanca corazon',
            slug: 'camiseta-basica-blanca-corazon',
            categoria: 'Camisetas',
            imagen: '/imagenes/p30.jpg',
            precio: 10,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 2.9,
            numReviews: 2,
            descripcion: 'Una elección esencial para tu vestuario, esta camiseta básica blanca combina simplicidad y estilo. Su diseño atemporal y versátil la convierte en la prenda perfecta para cualquier ocasión. '
        },
        {
            nombre: 'Zapatos turquesas de vestir',
            slug: 'zapatos-turquesas-de-vestir',
            categoria: 'Calzado',
            imagen: '/imagenes/p32.jpg',
            precio: 18,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 3.9,
            numReviews: 15,
            descripcion: 'Estos zapatos turquesas son una declaración de elegancia y estilo refinado. Fabricados con materiales de alta calidad, su diseño combina sofisticación y comodidad.'
        },
        {
            nombre: 'Botas verdes',
            slug: 'botas-verdes',
            categoria: 'Calzado',
            imagen: '/imagenes/p33.jpg',
            precio: 17,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 4.0,
            numReviews: 5,
            descripcion: 'Estas botas verdes son el complemento perfecto para destacar tu estilo con elegancia y versatilidad. Su color suave y neutro las convierte en un accesorio fácil de combinar con una variedad de atuendos. Ya sea para pasear por la ciudad o para una ocasión más formal, estas botas añaden un toque de sofisticación a tu look.'
        },
        {
            nombre: 'Abrigo largo negro',
            slug: 'abrigo-largo-negro',
            categoria: 'Abrigos',
            imagen: '/imagenes/p34.jpg',
            precio: 40,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 4.6,
            numReviews: 15,
            descripcion: 'Envuélvete en estilo con este elegante abrigo negro. Su diseño clásico y atemporal lo convierte en una pieza imprescindible para tu guardarropa. Confeccionado con atención a los detalles, este abrigo destaca por su versatilidad y capacidad para complementar una amplia variedad de conjuntos.'
        },
        {
            nombre: 'Zapatos marrones de vestir',
            slug: 'zapatos-marrones-de-vestir',
            categoria: 'Calzado',
            imagen: '/imagenes/p35.jpg',
            precio: 23,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 3.1,
            numReviews: 18,
            descripcion: 'Estos zapatos marrones son una declaración de elegancia y estilo refinado. Fabricados con materiales de alta calidad, su diseño combina sofisticación y comodidad.'
        },
        {
            nombre: 'Jersei de punto marron',
            slug: 'jersei-de-punto-marron',
            categoria: 'Jerseis',
            imagen: '/imagenes/p36.jpg',
            precio: 30,
            numeroEnStock: 25,
            marca: 'Untilted',
            valoracion: 4.2,
            numReviews: 18,
            descripcion: 'Este jersey de punto marron es la elección perfecta para mantenerte abrigado con estilo. Su diseño clásico y versátil lo convierte en un básico esencial para tu guardarropa. Fabricado con un tejido suave y cómodo, este jersey te brinda calidez sin renunciar al look elegante.'
        },
        {
            nombre: 'Abrigo largo blanco',
            slug: 'abrigo-largo-blanco',
            categoria: 'Abrigos',
            imagen: '/imagenes/p34.jpg',
            precio: 40,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 3.9,
            numReviews: 21,
            descripcion: 'Envuélvete en estilo con este elegante abrigo blanco. Su diseño clásico y atemporal lo convierte en una pieza imprescindible para tu guardarropa. Confeccionado con atención a los detalles, este abrigo destaca por su versatilidad y capacidad para complementar una amplia variedad de conjuntos.'
        },
        {
            nombre: 'Zapatos marrones elegantes',
            slug: 'zapatos-marrones-elegantes',
            categoria: 'Calzado',
            imagen: '/imagenes/p38.jpg',
            precio: 25,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 3.5,
            numReviews: 7,
            descripcion: 'Estos zapatos marrones son una declaración de elegancia y estilo refinado. Fabricados con materiales de alta calidad, su diseño combina sofisticación y comodidad.'
        },
        {
            nombre: 'Pantalones tejanos negros',
            slug: 'pantalones-tejanos-negros',
            categoria: 'Pantalones',
            imagen: '/imagenes/p39.jpg',
            precio: 12,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 2.5,
            numReviews: 7,
            descripcion: 'Estos tejanos negros son la opción perfecta para un estilo casual y cómodo. Confeccionados con un denim resistente pero suave, estos vaqueros ofrecen versatilidad y durabilidad.'
        },
        {
            nombre: 'Zapatos ocres',
            slug: 'zapatos-ocres',
            categoria: 'Calzado',
            imagen: '/imagenes/p40.jpg',
            precio: 20,
            numeroEnStock: 24,
            marca: 'Untilted',
            valoracion: 4.1,
            numReviews: 10,
            descripcion: 'Estos zapatos ocres son una declaración de elegancia y estilo refinado. Fabricados con materiales de alta calidad, su diseño combina sofisticación y comodidad.'
        },
        {
            nombre: 'Pantalones amarillos',
            slug: 'pantalones-amarillos',
            categoria: 'Pantalones',
            imagen: '/imagenes/p41.jpg',
            precio: 25,
            numeroEnStock: 12,
            marca: 'Untilted',
            valoracion: 3.5,
            numReviews: 8,
            descripcion: 'Estos pantalones amarillos son la combinación perfecta de comodidad y estilo. Confeccionados en un tono azul vibrante, añadirán un toque fresco a tu colección de ropa. Su diseño versátil los convierte en la elección ideal tanto para ocasiones casuales como para eventos más formales.'
        },
        {
            nombre: 'Camiseta básica rosa',
            slug: 'camiseta-basica-rosa',
            categoria: 'Camisetas',
            imagen: '/imagenes/p42.jpg',
            precio: 10,
            numeroEnStock: 25,
            marca: 'Untilted',
            valoracion: 3.9,
            numReviews: 12,
            descripcion: 'Una elección esencial para tu vestuario, esta camiseta básica rosa combina simplicidad y estilo. Su diseño atemporal y versátil la convierte en la prenda perfecta para cualquier ocasión. '
        },
        {
            nombre: 'Camiseta básica roja',
            slug: 'camiseta-basica-roja',
            categoria: 'Camisetas',
            imagen: '/imagenes/p42.jpg',
            precio: 10,
            numeroEnStock: 25,
            marca: 'Untilted',
            valoracion: 4.0,
            numReviews: 11,
            descripcion: 'Una elección esencial para tu vestuario, esta camiseta básica roja combina simplicidad y estilo. Su diseño atemporal y versátil la convierte en la prenda perfecta para cualquier ocasión. '
        },
        {

            nombre: 'Pantalones negros',
            slug: 'pantalones-negros',
            categoria: 'Pantalones',
            imagen: '/imagenes/p44.jpg',
            precio: 20,
            numeroEnStock: 30,
            marca: 'Untilted',
            valoracion: 3.8,
            numReviews: 10,
            descripcion: 'Estos elegantes pantalones negros son una pieza versátil y atemporal que puede adaptarse a una variedad de ocasiones. Confeccionados con un tejido de alta calidad, ofrecen comodidad y estilo en un solo paquete. Su corte favorecedor resalta la figura mientras proporciona libertad de movimiento.'
        },
        {

            nombre: 'Pantalones de cuadros grises',
            slug: 'pantalones-de-cuadros-grises',
            categoria: 'Pantalones',
            imagen: '/imagenes/p46.jpg',
            precio: 27,
            numeroEnStock: 30,
            marca: 'Untilted',
            valoracion: 4.7,
            numReviews: 21,
            descripcion: 'Estos elegantes pantalones grises de cuadros son la elección perfecta para un estilo casual pero refinado. El patrón de cuadros sutiles agrega un toque de sofisticación a tu atuendo, ofreciendo una opción versátil que se adapta a diversas ocasiones. '
        },
        {
            nombre: 'Camiseta básica turquesa oscuro',
            slug: 'camiseta-basica-turquesa-oscuro',
            categoria: 'Camisetas',
            imagen: '/imagenes/p472.jpg',
            precio: 10,
            numeroEnStock: 25,
            marca: 'Untilted',
            valoracion: 4.0,
            numReviews: 11,
            descripcion: 'Una elección esencial para tu vestuario, esta camiseta básica turquesa oscuro combina simplicidad y estilo. Su diseño atemporal y versátil la convierte en la prenda perfecta para cualquier ocasión. '
        },
        {
            nombre: 'Jersei azul a rayas de cuello alto',
            slug: 'jersei-azul-a-rayas-de-cuello-alto',
            categoria: 'Jerseis',
            imagen: '/imagenes/p48.jpg',
            precio: 27,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 4.1,
            numReviews: 12,
            descripcion: 'Este jersey azul a rayas de cuello alto es la elección perfecta para mantenerte abrigado con estilo. Su diseño clásico y versátil lo convierte en un básico esencial para tu guardarropa. Fabricado con un tejido suave y cómodo, este jersey te brinda calidez sin renunciar al look elegante.'
        },
        {
            nombre: 'Pantalones tejanos ajustados',
            slug: 'pantalones-tejanos-ajustados',
            categoria: 'Pantalones',
            imagen: '/imagenes/p49.jpg',
            precio: 20,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 2.4,
            numReviews: 7,
            descripcion: 'Estos tejanos azules ajustados son la opción perfecta para un estilo casual y cómodo. Confeccionados con un denim resistente pero suave, estos vaqueros ofrecen versatilidad y durabilidad.'
        },
        {
            nombre: 'Botas altas marrones',
            slug: 'botas-altas-marrones',
            categoria: 'Calzado',
            imagen: '/imagenes/p50.jpg',
            precio: 23,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 3.8,
            numReviews: 10,
            descripcion: 'Estas botas altas marrones son el complemento perfecto para destacar tu estilo con elegancia y versatilidad. Su color suave y neutro las convierte en un accesorio fácil de combinar con una variedad de atuendos. Ya sea para pasear por la ciudad o para una ocasión más formal, estas botas añaden un toque de sofisticación a tu look.'
        },
        {
            nombre: 'Zapatillas marrones y blancas',
            slug: 'zapatillas-marrones-y-blancas',
            categoria: 'Calzado',
            imagen: '/imagenes/p51.jpg',
            precio: 15,
            numeroEnStock: 30,
            marca: 'Untilted',
            valoracion: 3.5,
            numReviews: 12,
            descripcion: 'Estas zapatillas combinan a la perfección estilo y comodidad. Con un atractivo diseño en marrón y blanco, estas zapatillas son ideales para complementar tu estilo cotidiano. La combinación de colores neutros las hace versátiles, fácilmente combinables con una variedad de conjuntos.'
        },
        {
            nombre: 'Zapatos marrones',
            slug: 'zapatos-marrones',
            categoria: 'Calzado',
            imagen: '/imagenes/p52.jpg',
            precio: 40,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 4.2,
            numReviews: 13,
            descripcion: 'Estos zapatos marrones son una declaración de elegancia y estilo refinado. Fabricados con materiales de alta calidad, su diseño combina sofisticación y comodidad.'
        },
        {
            nombre: 'Botas de cuero marrones',
            slug: 'botas-de-cuero-marrones',
            categoria: 'Calzado',
            imagen: '/imagenes/p53.jpg',
            precio: 39,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 4.1,
            numReviews: 19,
            descripcion: 'Estas botas de cuero marrones son el complemento perfecto para destacar tu estilo con elegancia y versatilidad. Su color suave y neutro las convierte en un accesorio fácil de combinar con una variedad de atuendos. Ya sea para pasear por la ciudad o para una ocasión más formal, estas botas añaden un toque de sofisticación a tu look.'
        },
        {
            nombre: 'Pantalones tejanos oscuros',
            slug: 'pantalones-tejanos-oscuros',
            categoria: 'Pantalones',
            imagen: '/imagenes/p54.jpg',
            precio: 13,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 2.1,
            numReviews: 8,
            descripcion: 'Estos tejanos oscuros son la opción perfecta para un estilo casual y cómodo. Confeccionados con un denim resistente pero suave, estos vaqueros ofrecen versatilidad y durabilidad.'
        },
        {
            nombre: 'Botas de montaña marrones',
            slug: 'botas-de-montaña-marrones',
            categoria: 'Calzado',
            imagen: '/imagenes/p56.jpg',
            precio: 30,
            numeroEnStock: 25,
            marca: 'Untilted',
            valoracion: 3.6,
            numReviews: 9,
            descripcion: 'Estas botas de montaña marrones son el complemento perfecto para destacar tu estilo con elegancia y versatilidad. Su color suave y neutro las convierte en un accesorio fácil de combinar con una variedad de atuendos. Ya sea para pasear por la ciudad o para una ocasión más formal, estas botas añaden un toque de sofisticación a tu look.'
        },
        {
            nombre: 'Botas amarillas',
            slug: 'botas-amarillas',
            categoria: 'Calzado',
            imagen: '/imagenes/p57.jpg',
            precio: 35,
            numeroEnStock: 25,
            marca: 'Untilted',
            valoracion: 4.8,
            numReviews: 16,
            descripcion: 'Estas botas amarillas son el complemento perfecto para destacar tu estilo con elegancia y versatilidad. Su color suave y neutro las convierte en un accesorio fácil de combinar con una variedad de atuendos. Ya sea para pasear por la ciudad o para una ocasión más formal, estas botas añaden un toque de sofisticación a tu look.'
        },
        {
            nombre: 'Zapatos de vestir marrones',
            slug: 'zapatos-de-vestir-marrones',
            categoria: 'Calzado',
            imagen: '/imagenes/p58.jpg',
            precio: 45,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 3.8,
            numReviews: 12,
            descripcion: 'Estos zapatos de vestir marrones son una declaración de elegancia y estilo refinado. Fabricados con materiales de alta calidad, su diseño combina sofisticación y comodidad.'
        },
        {
            nombre: 'Zapatillas rojas y blancas',
            slug: 'zapatillas-rojas-y-blancas',
            categoria: 'Calzado',
            imagen: '/imagenes/p59.jpg',
            precio: 15,
            numeroEnStock: 30,
            marca: 'Untilted',
            valoracion: 3.7,
            numReviews: 15,
            descripcion: 'Estas zapatillas combinan a la perfección estilo y comodidad. Con un atractivo diseño en rojo y blanco, estas zapatillas son ideales para complementar tu estilo cotidiano. La combinación de colores neutros las hace versátiles, fácilmente combinables con una variedad de conjuntos.'
        },
        {
            nombre: 'Pantalones tejanos fit',
            slug: 'pantalones-tejanos-fit',
            categoria: 'Pantalones',
            imagen: '/imagenes/p60.jpg',
            precio: 15,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 3.2,
            numReviews: 7,
            descripcion: 'Estos tejanos azules fit son la opción perfecta para un estilo casual y cómodo. Confeccionados con un denim resistente pero suave, estos vaqueros ofrecen versatilidad y durabilidad.'
        },
        {
            nombre: 'Pantalones tejanos azul claro',
            slug: 'pantalones-tejanos-azul-claro',
            categoria: 'Pantalones',
            imagen: '/imagenes/p61.jpg',
            precio: 15,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 3.9,
            numReviews: 12,
            descripcion: 'Estos tejanos azules claros son la opción perfecta para un estilo casual y cómodo. Confeccionados con un denim resistente pero suave, estos vaqueros ofrecen versatilidad y durabilidad.'
        },
        {
            nombre: 'Camisa de cuadros azul y blanco',
            slug: 'camisa-de-cuadros-azul-y-blanco',
            categoria: 'Camisas',
            imagen: '/imagenes/p62.jpg',
            precio: 25,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 3.2,
            numReviews: 16,
            descripcion: 'Esta camisa de cuadros es una mezcla perfecta de estilo casual y elegancia relajada. El patrón de cuadros, en tonos armoniosos, aporta un toque de dinamismo a la prenda, mientras que la paleta de colores cuidadosamente seleccionada garantiza una apariencia equilibrada.'
        },
        {
            nombre: 'Camisa morada clara',
            slug: 'camisa-morada-clara',
            categoria: 'Camisas',
            imagen: '/imagenes/p63.jpg',
            precio: 27,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 4.7,
            numReviews: 21,
            descripcion: 'Esta camisa morada para hombre es la elección perfecta para destacar con elegancia. Confeccionada en un tejido suave y cómodo, su color morado agrega un toque distintivo a tu vestuario. Ya sea para una ocasión formal o para un look más casual, esta camisa se adapta a diversas situaciones con estilo.'
        },
        {
            nombre: 'Camiseta sencilla blanca',
            slug: 'camiseta-sencilla-blanca',
            categoria: 'Camisetas',
            imagen: '/imagenes/p64.jpg',
            precio: 9,
            numeroEnStock: 25,
            marca: 'Untilted',
            valoracion: 4.0,
            numReviews: 9,
            descripcion: 'Una elección esencial para tu vestuario, esta camiseta sencilla blanca combina simplicidad y estilo. Su diseño atemporal y versátil la convierte en la prenda perfecta para cualquier ocasión. '
        },
        {
            nombre: 'Abrigo marron',
            slug: 'abrigo-marron',
            categoria: 'Abrigos',
            imagen: '/imagenes/p65.jpg',
            precio: 40,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 4.3,
            numReviews: 13,
            descripcion: 'Envuélvete en estilo con este elegante abrigo marron. Su diseño clásico y atemporal lo convierte en una pieza imprescindible para tu guardarropa. Confeccionado con atención a los detalles, este abrigo destaca por su versatilidad y capacidad para complementar una amplia variedad de conjuntos.'
        },
        {
            nombre: 'Falda negra básica',
            slug: 'falda-negra-basica',
            categoria: 'Faldas',
            imagen: '/imagenes/p66.jpg',
            precio: 15,
            numeroEnStock: 15,
            marca: 'Untilted',
            valoracion: 4.6,
            numReviews: 15,
            descripcion: 'Esta falda negra básica para hombre redefine la moda con un toque moderno y vanguardista. Confeccionada con un tejido ligero y cómodo, esta prenda desafía las convenciones tradicionales de la moda masculina. El diseño simple y versátil de la falda la convierte en una pieza clave para expresar un estilo único y audaz.'
        },
        {

            nombre: 'Pantalones elegantes negros',
            slug: 'pantalones-elegantes-negros',
            categoria: 'Pantalones',
            imagen: '/imagenes/p67.jpg',
            precio: 30,
            numeroEnStock: 30,
            marca: 'Untilted',
            valoracion: 4.3,
            numReviews: 12,
            descripcion: 'Estos elegantes pantalones negros son una pieza versátil y atemporal que puede adaptarse a una variedad de ocasiones. Confeccionados con un tejido de alta calidad, ofrecen comodidad y estilo en un solo paquete. Su corte favorecedor resalta la figura mientras proporciona libertad de movimiento.'
        },
        {
            nombre: 'Camiseta blanca faro',
            slug: 'camiseta-blanca-faro',
            categoria: 'Camisetas',
            imagen: '/imagenes/p68.jpg',
            precio: 15,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 3.7,
            numReviews: 11,
            descripcion: 'Esta camiseta blanca te ofrece un estilo fresco y único con un toque marítimo. En la parte posterior, destaca un faro, símbolo de orientación y aventura. El contraste entre el blanco puro de la camiseta y la detallada imagen del faro crea un impacto visual cautivador.'
        },
        {
            nombre: 'Abrigo claro',
            slug: 'abrigo-claro',
            categoria: 'Abrigos',
            imagen: '/imagenes/p69.jpg',
            precio: 35,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 3.8,
            numReviews: 17,
            descripcion: 'Envuélvete en estilo con este elegante abrigo claro. Su diseño clásico y atemporal lo convierte en una pieza imprescindible para tu guardarropa. Confeccionado con atención a los detalles, este abrigo destaca por su versatilidad y capacidad para complementar una amplia variedad de conjuntos.'
        },
        {
            nombre: 'Abrigo negro de pana',
            slug: 'abrigo-negro-de-pana',
            categoria: 'Abrigos',
            imagen: '/imagenes/p70.jpg',
            precio: 40,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 3.7,
            numReviews: 15,
            descripcion: 'Envuélvete en estilo con este elegante abrigo negro de pana. Su diseño clásico y atemporal lo convierte en una pieza imprescindible para tu guardarropa. Confeccionado con atención a los detalles, este abrigo destaca por su versatilidad y capacidad para complementar una amplia variedad de conjuntos.'
        },
        {
            nombre: 'Camiseta sencilla negra',
            slug: 'camiseta-sencilla-negra',
            categoria: 'Camisetas',
            imagen: '/imagenes/p71.jpg',
            precio: 12,
            numeroEnStock: 20,
            marca: 'Untilted',
            valoracion: 3.5,
            numReviews: 5,
            descripcion: 'Esta camiseta negra es la elección clásica para cualquier ocasión. Con su diseño atemporal y versátil, se adapta fácilmente a tu estilo personal. La suavidad de su tela proporciona comodidad durante todo el día, convirtiéndola en una opción perfecta para cualquier actividad, ya sea informal o elegante.'
        },
    ]
}

export default data;